-- A suite principal names ONE agent — that is the premise `agents_external_pair` (migration
-- 0003) already leans on, and the premise the whole organisation plane depends on. Nothing so
-- far enforced it: `findAgentByExternal` ran `.first()` with no `ORDER BY`, so two agents
-- (in the same tenant, or different ones) could both write the same `external_id`, and whichever
-- row SQLite happened to return would quietly win superpipeline's hub-token resolution — the other's
-- mapping effectively vanished, with nothing anywhere reporting it.
--
-- PARTIAL index, not a plain UNIQUE column constraint: the pair is `NULL, NULL` for every agent
-- nobody has ever linked — which is every agent in a standalone superpipeline, and every agent today
-- — and a bare UNIQUE(external_source, external_id) would either reject every second unmapped
-- agent (SQLite does NOT treat two NULLs as equal for uniqueness — this would actually be safe on
-- that point) or, worse, be the kind of constraint a future column default could quietly break.
-- Spelling out `WHERE external_id IS NOT NULL` says directly what migration 0003's comment
-- already promised: NULL is the normal, unconstrained state, and only an actual claim on a
-- principal is what this index polices.
--
-- `external_source` is part of the index (not just `external_id`) for the same reason it is part
-- of every other lookup and every other constraint on this pair: an id is only meaningful paired
-- with the system that minted it. Today there is exactly one source ('org-plane'), but the index
-- does not assume that stays true.
CREATE UNIQUE INDEX agents_external_pair_unique ON agents(external_source, external_id) WHERE external_id IS NOT NULL;
